trigger:
  - main

pr:
  - main

name: $(Date:yyyy.MM.dd)-$(BuildID)

resources:
  repositories:
    - repository: self
      type: git
      ref: main

jobs:
  - job: Client
    displayName: Website
    pool:
      vmImage: ubuntu-latest

    steps:
      - checkout: self
        clean: true

      - task: UseNode@1
        displayName: Use Node 18.18.x
        inputs:
          version: 18.18.x

      - task: Npm@1
        displayName: Install packages
        inputs:
          verbose: false

      - task: qetza.replacetokens.replacetokens-task.replacetokens@3
        displayName: Update GA tag
        inputs:
          rootDirectory: "src"
          targetFiles: "**/index.html"
          escapeType: none
          tokenPrefix: __
          tokenSuffix: __

      - powershell: |
          Write-Host "Target folder: $(Pipeline.Workspace)/s/src/"
          Write-Host "Replacing YYYY.MM.DD with $(Build.BuildNumber) ..."

          $FilesToChange = Get-ChildItem -Path $(Pipeline.Workspace)/s/src/*.* -Recurse -Force  |  Select-String -Pattern "YYYY.MM.DD" -AllMatches | Foreach {$_.Path} | Select-Object -Unique
          foreach ($SingleFile in $FilesToChange)
          {
              (Get-Content $SingleFile -Encoding UTF8) -replace "YYYY.MM.DD", "$(Build.BuildNumber)" | Set-Content $SingleFile
              Write-Host $SingleFile
          }
          Write-Host "... Done!"
        displayName: 'Add cache markers'

      - task: Npm@1
        displayName: Build SSR app
        inputs:
          command: custom
          verbose: false
          customCommand: run build:ssr

      - task: ArchiveFiles@2
        displayName: Stage browser artifacts
        inputs:
          rootFolderOrFile: dist/browser
          includeRootFolder: false
          archiveFile: $(Build.ArtifactStagingDirectory)/Website.zip

      - task: ArchiveFiles@2
        displayName: Stage server artifacts
        inputs:
          rootFolderOrFile: dist/server
          includeRootFolder: false
          archiveFile: $(Build.ArtifactStagingDirectory)/Server.zip

      - task: PublishBuildArtifacts@1
        displayName: Save artifacts
