trigger:
  - main

pr:
  - main

name: $(Date:yyyy.MM.dd)-$(BuildID)

resources:
  repositories:
    - repository: self
      type: git
      ref: main

jobs:
  - job: Client
    displayName: Website
    pool:
      vmImage: ubuntu-latest

    steps:
      - checkout: self
        clean: true

      - task: UseNode@1
        displayName: Use Node 18.16.x
        inputs:
          version: 18.16.x

      - task: Npm@1
        displayName: Install packages
        inputs:
          verbose: false

      - task: qetza.replacetokens.replacetokens-task.replacetokens@3
        displayName: Update GA tag
        inputs:
          rootDirectory: "src"
          targetFiles: "**/index.html"
          escapeType: none
          tokenPrefix: __
          tokenSuffix: __

      - powershell: |
          $DateMarker = Get-Date -Format "yyyy.MM.dd"
          $FilesToChange = Get-ChildItem -Path $(Pipeline.Workspace)/s/src/*.* -Recurse -Force  |  Select-String -Pattern "YYYY.MM.DD" -AllMatches | Foreach {$_.Path} | Select-Object -Unique

          Write-Host "------------------------------------------------------------"
          Write-Host "Add $DateMarker markers, $(Pipeline.Workspace)/s/src"
          Write-Host "------------------------------------------------------------"

          foreach ($SingleFile in $FilesToChange)
          {
              (Get-Content $SingleFile -Encoding UTF8) -replace 'YYYY.MM.DD', $DateMarker | Set-Content $SingleFile
              Write-Host "Updated for: " $SingleFile
              Write-Host " -----------------------------------"
          }
        displayName: 'Add version markers'

      - task: Npm@1
        displayName: Build
        inputs:
          command: custom
          verbose: false
          customCommand: run build.prod

      - task: ArchiveFiles@2
        displayName: Stage artifacts
        inputs:
          rootFolderOrFile: dist/app
          includeRootFolder: false
          archiveFile: $(Build.ArtifactStagingDirectory)/Website.zip

      - task: PublishBuildArtifacts@1
        displayName: Save artifacts
