name: Deploy website

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

concurrency:
  group: ${{ github.ref }}

jobs:
  deploy:
    name: Cloudflare Pages
    runs-on: ubuntu-latest

    environment:
      name: website

    steps:

      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Define tag
        id: tag
        run: echo "version=$(date +'%Y.%m.%d')-${{ github.run_number }}" >> $GITHUB_OUTPUT

      - name: Replace cache markers
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "YYYY.MM.DD"
          replace: "${{ steps.tag.outputs.version }}"
          regex: false

      - name: Install packages
        run: npm install

      - name: Build site (production)
        if: github.ref == 'refs/heads/main'
        run: npm run build.prod

      - name: Build site (preview)
        if: github.ref != 'refs/heads/main'
        run: npm run build

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_KEY }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: ${{ vars.CLOUDFLARE_PROJECT_NAME }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          directory: dist/app
          wranglerVersion: 'latest'

      - name: Tag and release note
        uses: ncipollo/release-action@v1
        if: github.ref == 'refs/heads/main'
        with:
          generateReleaseNotes: true
          draft: true
          tag: ${{ steps.tag.outputs.version }}
          commit: ${{ github.ref_name }}
