name: Deploy website

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

concurrency:
  group: cloudflare-pages

jobs:
  deploy:
    name: Cloudflare Pages
    runs-on: ubuntu-latest

    environment:
      name: cloudflare-pages

    steps:

      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          cache: 'npm'

      - name: Add cache markers
        shell: pwsh
        working-directory: ./src
        run: |
          Write-Host "Replacing YYYY.MM.DD with ${{ github.run_id }} ..."

          $FilesToChange = Get-ChildItem -Path *.* -Recurse -Force  |  Select-String -Pattern "YYYY.MM.DD" -AllMatches | Foreach {$_.Path} | Select-Object -Unique
          foreach ($SingleFile in $FilesToChange)
          {
              (Get-Content $SingleFile -Encoding UTF8) -replace "YYYY.MM.DD", "${{ github.run_id }}" | Set-Content $SingleFile
              Write-Host $SingleFile
          }
          Write-Host "... Done!"



      - name: Define tag
        id: tag
        run: echo "tag=$(date +'%Y.%m.%d')-${{ github.run_id }}" >> $GITHUB_OUTPUT

      - name: Show tag
        run: echo "${{ steps.tag.outputs.tag }}"

      - name: Tag and draft release note
        uses: ncipollo/release-action@v1
        if: github.ref == 'refs/heads/main'
        with:
          generateReleaseNotes: true
          draft: true
          tag: ${{ steps.tag.outputs.tag }}
          commit: ${{ github.ref_name }}
